config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :courses, only: [:index, :show]
  namespace :instructor do
    resources :courses, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
   if @course.valid?
    redirect_to instructor_course_path(@course)
   else
    render :new, status: :unprocessable_entity
   end
  end

  def show
    @course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn</h1>
  <br />


<% @courses.each do |course| %>
    <h2 class="text-center">
    <%= link_to course.title, course_path(course) %>
    </h2>
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 col-12 text-center">
        <%= link_to 'More Details', course_path(course), class: 'btn btn-primary btn-block' %>
      </div>
    </div>
    <br class="clr" />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah box col-10 offset-1">
  <h1><%= @course.title %> </h1>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
       <%= number_to_currency @course.cost %>
      </span>
     <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Edit', instructor_course_path(@course), class: 'btn btn-info btn-medium' %>
      <% end %>
    </div>

    <div class="col-sm-8 col-12">
    <%= @course.description %>
    </div>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add A Course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary btn-block' %>
    <br />
    <% end %>
    <br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= @course.title %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reflections</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="flex-content-container">
    <nav class="navbar navbar-light" style="background-color: #9ACFFC;">
  <!-- Navbar content -->
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">Reflections</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to 'Courses', courses_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
               <li class="nav-item">
                 <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
          <% else %>
              <li class="nav-item">
                 <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                 <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
          <% end %>
        </ul>

        </div>
      </nav>
  </nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>

  </div>
  <div id="footer">
    <div class="container">
      <b>Teachers Area</b>
      <br />
      <%= link_to '--Teach A Course', new_instructor_course_path %>
    </div>
  </div>

  </body>
</html>

app/views/static_pages/index.html.erb
<div class="hero">
    <div class="frosty col-10 offset-1 text-center">
      <h1>Reflections From The Saddle</h1>
      <h2>Online Courses in Equestrian Endeavors</h2>
    </div>
</div>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
   <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <%= image_tag 'white.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
       <h3>Building Trust and Motivation</h3>
     </div>
   </div>
    <div class="carousel-item">
        <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
       <h3>Training With Rewards</h3>
      </div>
    </div>
      <div class="carousel-item">
        <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
        <div class="carousel-caption d-none d-md-block">
        <h3>Promoting Relaxation</h3>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
     <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br />
<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Relaxation</h3>
    <br />
    <p>Fostering Trust</p>
  </div>
  <div class="col-12 col-sm">
    <h3>Rewards</h3>
    <br />
    <p>Building Motivation</p>
  </div>
  <div class="col-12 col-sm">
    <h3>Compassion</h3>
    <br />
    <p>Practicing Gratitude</p>
  </div>
</div>